#!/bin/bash

DIR="/x/gm24385/chr19"
BC="guppy_4_0_11"
BAM="$DIR/$BC/margin/output.haplotagged.bam"
REF="$DIR/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
VCF="$DIR/$BC/margin_hp/output.phased.vcf.gz"

# run ReAligner
time python3 ../realign.py \
    $BAM \
    $REF \
    --vcf $VCF \
    --stats_dir ../stats \
    --contig chr19 \
    --contig_beg 1 \
    --contig_end 100000 \
    --splice_subs \
    --indels_only \
    realigned.bam

# update MD tags
~/NanoporeScripts/align ./realigned.bam $REF
