#!/bin/bash

DIR="/x/gm24385/chr19"
BC="guppy_4_0_11"
OUT="ra_hap"
# BAM="$DIR/$BC/$OUT/1_phased.bam"
# REF="$DIR/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
BAM="reads.bam"
REF="ref.fasta"

# run ReAligner
time python3 ../realign.py \
    $BAM \
    $REF \
    ./realigned.bam \
    --recalc_pileups \
    --contig ref \
    --stats_dir ../stats

# update MD tags
~/NanoporeScripts/align ./realigned.bam $REF
